MBRFClass :
    times :
        mandatory : true

MBRFProp :
    type :
        mandatory : true
        generators :
            firstname :
                mapping : "Generators\\FirstnameGenerator"
                group: "person"
            lastname :
                mapping : "Generators\\LastnameGenerator"
                group: "person"
            maleFirstname :
                mapping : "Generators\\MaleFirstnameGenerator"
                group: "person"
            femaleFirstname :
                mapping : "Generators\\FemaleFirstnameGenerator"
                group: "person"
            gender :
                mapping : "Generators\\GenderGenerator"
                group : "person"
            genderAbbrev:
                mapping : "Generators\\GenderAbbrevGenerator"
                group : "person"
            email :
                mapping : "Generators\\EmailGenerator"
                group: "person"
            companyEmail :
                mapping : "Generators\\CompanyEmailGenerator"
                group : "company"
            text :
                mapping : "Generators\\TextGenerator"
                group: "text"
    nullable :
    options :

MBRFOptions :
    regex :
