MBRF :
    MBRFClass :
        times :
            mandatory : true

    MBRFProp :
        type :
            mandatory : true
            generators :
                firstname :
                    mapping : "MikaelBrosset\\RandomFixturesBundle\\Generators\\FirstnameGenerator"
                    requires : "gender, maleFirstname, femaleLastname"
                lastname :
                    mapping : "MikaelBrosset\\RandomFixturesBundle\\Generators\\LastnameGenerator"
                    resource : "lastname"
                maleFirstname :
                    mapping : "MikaelBrosset\\RandomFixturesBundle\\Generators\\MaleFirstnameGenerator"
                    resource : "male-firstname"
                femaleFirstname :
                    mapping : "MikaelBrosset\\RandomFixturesBundle\\Generators\\FemaleFirstnameGenerator"
                    resource : "female-firstname"
                gender :
                    mapping : "MikaelBrosset\\RandomFixturesBundle\\Generators\\GenderGenerator"
                    resource : "gender"
                genderAbbrev :
                    mapping : "MikaelBrosset\\RandomFixturesBundle\\Generators\\GenderAbbrevGenerator"
                    requires : "gender"
                slug :
                    mapping : "MikaelBrosset\\RandomFixturesBundle\\Generators\\SlugGenerator"
                    requires : "firstname, lastname"
                email :
                    mapping : "MikaelBrosset\\RandomFixturesBundle\\Generators\\EmailGenerator"
                    requires: "firstname, lastname, companyName"
                text :
                    mapping : "MikaelBrosset\\RandomFixturesBundle\\Generators\\TextGenerator"
                shortText :
                    mapping : "MikaelBrosset\\RandomFixturesBundle\\Generators\\ShortTextGenerator"
                companyName :
                    mapping : "MikaelBrosset\\RandomFixturesBundle\\Generators\\CompanyNameGenerator"
        nullable :
        options :

    MBRFOptions :
        regex :
